Implement imports for PDB files (#10)
* Add dummy import pdb button

* Add dummy cpp file to copile

* Add JNIEXPORT to cpp, and Cpp.java

* Fix simple C++ func not working in android (it works!)

* Add directory to house VMD source

* Add gradle task before preBuild to fetch vmd source

* Remove redundant import

* Add TCL, attempt some compilation

* Remove unused trivial cpp program

* Document reason for -DNO_UNION_WAIT

* Fix compile errors for CFG_{INSTALL,RUNTIME}_* definitions

* Fix compile errors for missing -DTCL_CFGVAL_ENCODING

* Fix compile errors for missing -DTCL_LIBRARY -DTCL_PACKAGE_PATH

* Fix missing -DSTDC_HEADERS

* Fix values.h file not found for AtomParser.C

* Fix missing intstack.c

* Fix missing definition for log_android

* Fix undefined reference to vmdpcre_compile

* Fix missing vmdsock file

* Fix missing vmddlopen.c file

* Fix undefined reference to main

* Add android assets folder

* Add compiled vmd binary as android asset

* Set output dir according to arch

* Add init step copying vmd from assets to internal storage

* Run vmd on android successfully

* Progress towards rendering pdb file on android

* Add a proof of concept for async

* Wrap pdb render in AsyncTask, but nonfunctional

* Wrap glb render in AsyncTask

* Wrap obj renderer in AsyncTask

* Fix vmd unable to execute tcl

* Copy over TCL auxillary files

* i am so dumb

* Refactor FileIo in PdbRenderer to FileIo class

* Reorganise asset to internal dir structure

* Implement a recursive copy for directories

* Add molfile_plugins to build process

* Pass the compilation step for molfile_pugins

* Modularise CMakeLists.txt naively

* Pass compile step for molfile plugins

* Pass the linking step for molfile plugins

* Set molfile libraries to output at assets

* Fix copyAssetDirToInternalStorage not recursing properly

* Copy over molfile plugins, partially implemented PDB imports